version: '3.7'
services:

  users-srv:
    container_name: domainevents
    build: ../..
    ports:
      - "8080:8080"
    expose: 
      - 8080

  blog-srv:
    container_name: blog-srv
    build: ../../blog-srv
    ports:
      - "8081:8080"
    expose: 
      - 8080
